# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HereExploreExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Include the HERE SDK in the build using "pod"
  pod 'heresdk', :path => 'Frameworks'

  target 'HereExploreExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'heresdk', :path => 'Frameworks'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
     puts("add heresdk.xcframework reference to react-native-here-explore project.")
     installer.pods_project.targets.each do |target|
       if target.name  == "react-native-here-explore"
         puts("Found react-native-here-explore target.")
         all_filerefs = installer.pods_project.files
         all_filerefs.each do |fileref|
            if fileref.path.end_with? "heresdk.xcframework"
             puts("Found heresdk.xcframework fileref.")
             build_phase = target.frameworks_build_phase
             puts("Determining if react-native-here-explore build phase needs correction.")
             unless build_phase.files_references.include?(fileref)
               puts("Adding heresdk.xcframework to react-native-here-explore target")
               build_phase.add_file_reference(fileref)
             end
           end
         end
       end
     end
  end
end
